In [6]:
import pandas as pd
import sklearn as sk
import numpy as np
import seaborn as sns

In [8]:
data = pd.read_csv(r"C:\Users\WELCOME\Downloads\archive\Housing.csv")

In [9]:
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [10]:
data.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [11]:
data.shape


(545, 13)

In [12]:
data.describe()


price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [15]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [16]:
data.head(2)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished

In [19]:
y = data['price']
x = data.drop(columns = ['price'])

In [20]:
from sklearn.preprocessing import StandardScaler


In [25]:
scale = StandardScaler()

In [26]:
names = x.columns


In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [30]:
data.head(2)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished

In [31]:
data['mainroad'] = le.fit_transform(data['mainroad'])
data['guestroom'] = le.fit_transform(data['guestroom'])
data['basement'] = le.fit_transform(data['basement'])
data['hotwaterheating'] = le.fit_transform(data['hotwaterheating'])
data['airconditioning'] = le.fit_transform(data['airconditioning'])
data['prefarea'] = le.fit_transform(data['prefarea'])
data['furnishingstatus'] = le.fit_transform(data['furnishingstatus'])                                   

In [34]:
data.head()


price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0

In [35]:
y = data['price']
x = data.drop(columns = ['price'])

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
scale = StandardScaler()

In [38]:
names = x.columns

In [39]:
x = scale.fit_transform(x)

In [40]:
x

array([[ 1.04672629,  1.40341936,  1.42181174, ...,  1.51769249,
         1.80494113, -1.40628573],
       [ 1.75700953,  1.40341936,  5.40580863, ...,  2.67940935,
        -0.55403469, -1.40628573],
       [ 2.21823241,  0.04727831,  1.42181174, ...,  1.51769249,
         1.80494113, -0.09166185],
       ...,
       [-0.70592066, -1.30886273, -0.57018671, ..., -0.80574124,
        -0.55403469,  1.22296203],
       [-1.03338891,  0.04727831, -0.57018671, ..., -0.80574124,
        -0.55403469, -1.40628573],
       [-0.5998394 ,  0.04727831, -0.57018671, ..., -0.80574124,
        -0.55403469,  1.22296203]])

In [41]:
x = pd.DataFrame(x,columns = names)

In [42]:
x.head()

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
0  1.046726  1.403419   1.421812  1.378217  0.405623  -0.465315 -0.734539   
1  1.757010  1.403419   5.405809  2.532024  0.405623  -0.465315 -0.734539   
2  2.218232  0.047278   1.421812  0.224410  0.405623  -0.465315  1.361397   
3  1.083624  1.403419   1.421812  0.224410  0.405623  -0.465315  1.361397   
4  1.046726  1.403419  -0.570187  0.224410  0.405623   2.149083  1.361397   

   hotwaterheating  airconditioning   parking  prefarea  furnishingstatus  
0        -0.219265         1.472618  1.517692  1.804941         -1.406286  
1        -0.219265         1.472618  2.679409 -0.554035         -1.406286  
2        -0.219265        -0.679063  1.517692  1.804941         -0.091662  
3        -0.219265         1.472618  2.679409  1.804941         -1.406286  
4        -0.219265         1.472618  1.517692 -0.554035         -1.406286

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [45]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(436, 12)
(109, 12)
(436,)
(109,)


In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [47]:
dtree = DecisionTreeClassifier()
rand = RandomForestClassifier()

In [48]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [49]:
ytr = dtree.predict(x_train)

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [51]:
print(accuracy_score(y_train,ytr))

0.9908256880733946


In [52]:
print(confusion_matrix(y_train,ytr))

[[3 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 2]]


In [53]:
ytt = dtree.predict(x_test)

In [54]:
print(accuracy_score(y_test,ytt))

0.0


In [55]:
print(confusion_matrix(y_test,ytt))

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [56]:
rand.fit(x_train,y_train)

RandomForestClassifier()

In [57]:
ytr = rand.predict(x_train)

In [58]:
print(accuracy_score(y_train,ytr))

0.9908256880733946


In [59]:
print(confusion_matrix(y_train,ytr))

[[2 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 2]]


In [60]:
ytt = rand.predict(x_test)

In [61]:
print(accuracy_score(y_test,ytt))

0.009174311926605505


In [62]:
print(confusion_matrix(y_test,ytt))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [63]:
from sklearn.linear_model import LogisticRegression

In [64]:
logi = LogisticRegression()

In [65]:
logi.fit(x_train,y_train)

LogisticRegression()

In [66]:
ytr = logi.predict(x_train)

In [67]:
print(accuracy_score(y_train,ytr))

0.3646788990825688


In [68]:
ytt = logi.predict(x_test)

In [69]:
print(accuracy_score(y_test,ytt))

0.009174311926605505


In [70]:
from sklearn.neighbors import KNeighborsClassifier

In [71]:
knn = KNeighborsClassifier()

In [72]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [73]:
ytr = knn.predict(x_train)

In [74]:
print(accuracy_score(y_train,ytr))

0.1926605504587156


In [75]:
from sklearn.svm import SVC

In [76]:
svc = SVC()

In [77]:
svc.fit(x_train,y_train)

SVC()

In [78]:
ytr = svc.predict(x_train)

In [79]:
print(accuracy_score(y_train,ytr))

0.19495412844036697


In [80]:
ytt = svc.predict(x_test)

In [81]:
print(accuracy_score(y_test,ytt))

0.01834862385321101


In [82]:
import pickle

In [83]:
pickle.dump(rand,open("model.pkl","wb"))

In [84]:
data.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0

In [85]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['price'] = le.fit_transform(data['price'])

In [86]:
y = data['price']
x = data.drop(columns = ['price'])

In [87]:
names = x.columns

In [88]:
x = scale.fit_transform(x)

In [89]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size = 0.2)

In [90]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [91]:
rand = RandomForestRegressor()
dec = DecisionTreeRegressor()

In [92]:
rand.fit(x_train,y_train)

RandomForestRegressor()

In [93]:
dec.fit(x_train,y_train)

DecisionTreeRegressor()

In [94]:
pred = rand.predict(x_test)
pred1 = dec.predict(x_test)

In [95]:
from sklearn.metrics import mean_squared_error

In [96]:
np.sqrt(mean_squared_error(y_test,pred))

36.07412124664805

In [97]:
np.sqrt(mean_squared_error(y_test,pred1))

45.859703284268